### ISSUE TITLE
Command Context not compatible with JDA 5

### ISSUE THREAD

**Issue by HeshamSHY** [duncte123/botCommons#8] opened 2022-03-21 20:15 UTC
In JDA 5 they removed the `GuildMessageReceivedEvent`  and replaced it with `MessageReceivedEvent`, which makes the Command Context unusable in JDA 5

**Comment by duncte123** [comment] 2022-03-22 11:48
Duplicate of https://github.com/duncte123/botCommons/issues/7

**Closed as completed by duncte123** 2022-03-22 11:48 UTC
